// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBco1RwyRbJX7gFUncgaSJzUJcdm5Dqhs',
    appId: '1:243745432635:web:3aa244628b1ea06231a81e',
    messagingSenderId: '243745432635',
    projectId: 'job-find-search',
    authDomain: 'job-find-search.firebaseapp.com',
    storageBucket: 'job-find-search.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2zm1TsCNpgBY7LjYDf4DcLBbQuAFaO4s',
    appId: '1:243745432635:android:cfe68a4654a0401c31a81e',
    messagingSenderId: '243745432635',
    projectId: 'job-find-search',
    storageBucket: 'job-find-search.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoQFwC2-tC3XtZf6TCQgR2zDu9SqG_7LU',
    appId: '1:243745432635:ios:50328094c86f04de31a81e',
    messagingSenderId: '243745432635',
    projectId: 'job-find-search',
    storageBucket: 'job-find-search.appspot.com',
    iosBundleId: 'com.example.jobHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoQFwC2-tC3XtZf6TCQgR2zDu9SqG_7LU',
    appId: '1:243745432635:ios:50328094c86f04de31a81e',
    messagingSenderId: '243745432635',
    projectId: 'job-find-search',
    storageBucket: 'job-find-search.appspot.com',
    iosBundleId: 'com.example.jobHub',
  );
}
